spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    encoding: UTF-8
    cache: false

  messages:
    encoding: UTF-8

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

  api-docs:
    path: /v3/api-docs


openai:
  api-key: ${OPENAI_API_KEY}

server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

